# Generated by Django 2.2.10 on 2020-02-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=11, null=True)),
                ('bank_id', models.IntegerField(null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('district', models.CharField(max_length=40, null=True)),
                ('state', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
